print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Hola em dic moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
print("Moi")
